apiVersion: v1
kind: Service
metadata:
  name: lichen
spec:
  clusterIP: None
  selector:
    app: lichen
  ports:
    - port: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lichen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lichen
  template:
    metadata:
      labels:
        app: lichen
    spec:
      containers:
        - name: lichen
          image: ghcr.io/oliver-ni/lichen:latest
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lichen
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: dns01
spec:
  tls:
    - secretName: oliver-ni-cert
      hosts:
        - "lichen.oliver.ni"
  rules:
    - host: lichen.oliver.ni
      http:
        paths:
          - backend:
              serviceName: lichen
              servicePort: 4000
